sudo: enabled
dist: trusty
addons:
  apt:
    packages:
    - quilt
    - parted
    - realpath
    - qemu-user-static
    - debootstrap
    - zerofree
    - pxz
    - zip
    - dosfstools
    - bsdtar
    - libcap2-bin
    - grep
    - rsync
install: true
jobs:
  include:
  - stage: stage0
    script:
    - echo "hello"
    - echo "line2"
